spring:
    application:
        name= todolist
    data:
        mongodb:
            uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/DP
jwt:
    secret: QmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6
