spring:
    application:
        name= todolist
    data:
        mongodb:
            uri: mongodb+srv://103tmdt:103tmdt@cluster0.et7xk.mongodb.net/crawler?authSource=admin&replicaSet=atlas-w2zjyu-shard-0&w=majority&readPreference=primary&retryWrites=true&ssl=true
jwt:
    secret: QmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6
